package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1



/**
 * ActionsPerPlan generated by hbm2java
 */
public class ActionsPerPlan  implements java.io.Serializable {


     private int id;
     private Action action;
     private Plan plan;

    public ActionsPerPlan() {
    }

    public ActionsPerPlan(int id, Action action, Plan plan) {
       this.id = id;
       this.action = action;
       this.plan = plan;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Action getAction() {
        return this.action;
    }
    
    public void setAction(Action action) {
        this.action = action;
    }
    public Plan getPlan() {
        return this.plan;
    }
    
    public void setPlan(Plan plan) {
        this.plan = plan;
    }




}


