package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action  implements java.io.Serializable {


     private int id;
     private String name;
     private Set actionsPerPlans = new HashSet(0);
     private Set deliverables = new HashSet(0);

    public Action() {
    }

	
    public Action(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Action(int id, String name, Set actionsPerPlans, Set deliverables) {
       this.id = id;
       this.name = name;
       this.actionsPerPlans = actionsPerPlans;
       this.deliverables = deliverables;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getActionsPerPlans() {
        return this.actionsPerPlans;
    }
    
    public void setActionsPerPlans(Set actionsPerPlans) {
        this.actionsPerPlans = actionsPerPlans;
    }
    public Set getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(Set deliverables) {
        this.deliverables = deliverables;
    }




}


