package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Canton generated by hbm2java
 */
public class Canton  implements java.io.Serializable {


     private int id;
     private String name;
     private Set delivPerCants = new HashSet(0);

    public Canton() {
    }

	
    public Canton(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Canton(int id, String name, Set delivPerCants) {
       this.id = id;
       this.name = name;
       this.delivPerCants = delivPerCants;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDelivPerCants() {
        return this.delivPerCants;
    }
    
    public void setDelivPerCants(Set delivPerCants) {
        this.delivPerCants = delivPerCants;
    }




}


