package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1



/**
 * DelivPerCant generated by hbm2java
 */
public class DelivPerCant  implements java.io.Serializable {


     private int id;
     private Canton canton;
     private Deliverable deliverable;

    public DelivPerCant() {
    }

    public DelivPerCant(int id, Canton canton, Deliverable deliverable) {
       this.id = id;
       this.canton = canton;
       this.deliverable = deliverable;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Canton getCanton() {
        return this.canton;
    }
    
    public void setCanton(Canton canton) {
        this.canton = canton;
    }
    public Deliverable getDeliverable() {
        return this.deliverable;
    }
    
    public void setDeliverable(Deliverable deliverable) {
        this.deliverable = deliverable;
    }




}


