package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deliverable generated by hbm2java
 */
public class Deliverable  implements java.io.Serializable {


     private int id;
     private Action action;
     private KpiXtype kpiXtype;
     private Party party;
     private Userr userr;
     private String detail;
     private int kpiCant;
     private Date readyDate;
     private Set delivPerCants = new HashSet(0);

    public Deliverable() {
    }

	
    public Deliverable(int id, Action action, KpiXtype kpiXtype, Party party, Userr userr, String detail, int kpiCant, Date readyDate) {
        this.id = id;
        this.action = action;
        this.kpiXtype = kpiXtype;
        this.party = party;
        this.userr = userr;
        this.detail = detail;
        this.kpiCant = kpiCant;
        this.readyDate = readyDate;
    }
    public Deliverable(int id, Action action, KpiXtype kpiXtype, Party party, Userr userr, String detail, int kpiCant, Date readyDate, Set delivPerCants) {
       this.id = id;
       this.action = action;
       this.kpiXtype = kpiXtype;
       this.party = party;
       this.userr = userr;
       this.detail = detail;
       this.kpiCant = kpiCant;
       this.readyDate = readyDate;
       this.delivPerCants = delivPerCants;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Action getAction() {
        return this.action;
    }
    
    public void setAction(Action action) {
        this.action = action;
    }
    public KpiXtype getKpiXtype() {
        return this.kpiXtype;
    }
    
    public void setKpiXtype(KpiXtype kpiXtype) {
        this.kpiXtype = kpiXtype;
    }
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }
    public Userr getUserr() {
        return this.userr;
    }
    
    public void setUserr(Userr userr) {
        this.userr = userr;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public int getKpiCant() {
        return this.kpiCant;
    }
    
    public void setKpiCant(int kpiCant) {
        this.kpiCant = kpiCant;
    }
    public Date getReadyDate() {
        return this.readyDate;
    }
    
    public void setReadyDate(Date readyDate) {
        this.readyDate = readyDate;
    }
    public Set getDelivPerCants() {
        return this.delivPerCants;
    }
    
    public void setDelivPerCants(Set delivPerCants) {
        this.delivPerCants = delivPerCants;
    }




}


