package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * KpiXtype generated by hbm2java
 */
public class KpiXtype  implements java.io.Serializable {


     private int id;
     private String ente;
     private Set deliverables = new HashSet(0);

    public KpiXtype() {
    }

	
    public KpiXtype(int id, String ente) {
        this.id = id;
        this.ente = ente;
    }
    public KpiXtype(int id, String ente, Set deliverables) {
       this.id = id;
       this.ente = ente;
       this.deliverables = deliverables;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEnte() {
        return this.ente;
    }
    
    public void setEnte(String ente) {
        this.ente = ente;
    }
    public Set getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(Set deliverables) {
        this.deliverables = deliverables;
    }




}


