package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Party generated by hbm2java
 */
public class Party  implements java.io.Serializable {


     private int id;
     private String name;
     private String flagPath;
     private Set userrs = new HashSet(0);
     private Set deliverables = new HashSet(0);
     private Set plansPerParties = new HashSet(0);

    public Party() {
    }

	
    public Party(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Party(int id, String name, String flagPath, Set userrs, Set deliverables, Set plansPerParties) {
       this.id = id;
       this.name = name;
       this.flagPath = flagPath;
       this.userrs = userrs;
       this.deliverables = deliverables;
       this.plansPerParties = plansPerParties;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFlagPath() {
        return this.flagPath;
    }
    
    public void setFlagPath(String flagPath) {
        this.flagPath = flagPath;
    }
    public Set getUserrs() {
        return this.userrs;
    }
    
    public void setUserrs(Set userrs) {
        this.userrs = userrs;
    }
    public Set getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(Set deliverables) {
        this.deliverables = deliverables;
    }
    public Set getPlansPerParties() {
        return this.plansPerParties;
    }
    
    public void setPlansPerParties(Set plansPerParties) {
        this.plansPerParties = plansPerParties;
    }




}


