package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1



/**
 * PlansPerParty generated by hbm2java
 */
public class PlansPerParty  implements java.io.Serializable {


     private int id;
     private Party party;
     private Plan plan;

    public PlansPerParty() {
    }

    public PlansPerParty(int id, Party party, Plan plan) {
       this.id = id;
       this.party = party;
       this.plan = plan;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }
    public Plan getPlan() {
        return this.plan;
    }
    
    public void setPlan(Plan plan) {
        this.plan = plan;
    }




}


