package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private int id;
     private String name;
     private Set actionsPerPlans = new HashSet(0);
     private Set plansPerParties = new HashSet(0);

    public Plan() {
    }

	
    public Plan(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Plan(int id, String name, Set actionsPerPlans, Set plansPerParties) {
       this.id = id;
       this.name = name;
       this.actionsPerPlans = actionsPerPlans;
       this.plansPerParties = plansPerParties;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getActionsPerPlans() {
        return this.actionsPerPlans;
    }
    
    public void setActionsPerPlans(Set actionsPerPlans) {
        this.actionsPerPlans = actionsPerPlans;
    }
    public Set getPlansPerParties() {
        return this.plansPerParties;
    }
    
    public void setPlansPerParties(Set plansPerParties) {
        this.plansPerParties = plansPerParties;
    }




}


