package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RoleUser generated by hbm2java
 */
public class RoleUser  implements java.io.Serializable {


     private int id;
     private String type;
     private Set userrs = new HashSet(0);

    public RoleUser() {
    }

	
    public RoleUser(int id, String type) {
        this.id = id;
        this.type = type;
    }
    public RoleUser(int id, String type, Set userrs) {
       this.id = id;
       this.type = type;
       this.userrs = userrs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getUserrs() {
        return this.userrs;
    }
    
    public void setUserrs(Set userrs) {
        this.userrs = userrs;
    }




}


