package relation;
// Generated 28-feb-2022 23:44:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userr generated by hbm2java
 */
public class Userr  implements java.io.Serializable {


     private int id;
     private Party party;
     private RoleUser roleUser;
     private String name;
     private String photoPath;
     private String bio;
     private Set deliverables = new HashSet(0);

    public Userr() {
    }

	
    public Userr(int id, Party party, RoleUser roleUser, String name, String bio) {
        this.id = id;
        this.party = party;
        this.roleUser = roleUser;
        this.name = name;
        this.bio = bio;
    }
    public Userr(int id, Party party, RoleUser roleUser, String name, String photoPath, String bio, Set deliverables) {
       this.id = id;
       this.party = party;
       this.roleUser = roleUser;
       this.name = name;
       this.photoPath = photoPath;
       this.bio = bio;
       this.deliverables = deliverables;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }
    public RoleUser getRoleUser() {
        return this.roleUser;
    }
    
    public void setRoleUser(RoleUser roleUser) {
        this.roleUser = roleUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
    public Set getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(Set deliverables) {
        this.deliverables = deliverables;
    }




}


